language: cpp
compiler:
  - clang
  - gcc
before_script:
# gcc 4.7
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test --yes
  - sudo add-apt-repository ppa:boost-latest/ppa --yes
  - sudo add-apt-repository ppa:irie/openimageio --yes
  - sudo apt-get update -qq
  - sudo apt-get build-dep openimageio
  - sudo apt-get install git cmake gcc-4.9
  - sudo apt-get install libboost1.54-dev libboost-filesystem1.54-dev libboost-regex1.54-dev libboost-system1.54-dev libboost-thread1.54-dev
  - git clone -b RB-1.4 https://github.com/OpenImageIO/oiio.git
  - cd oiio
  - git apply ../oiio.patch
  - sudo make USE_QT=0 USE_OPENGL=0 USE_PYTHON=0 USE_FIELD3D=0 USE_OPENJPEG=0 USE_GIF=0 USE_OCIO=0 USE_OPENSSL=0 USE_LIBRAW=0 NOTHREADS=0 OIIO_BUILD_TOOLS=0 OIIO_BUILD_TESTS=0 -e dist_dir= INSTALLDIR=/usr
  - cd ..
script:
  - cmake ./
  - make
