language: cpp
compiler:
  - clang
  - gcc
before_script:
# gcc 4.7
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test --yes
  - sudo add-apt-repository ppa:irie/openimageio --yes
  - sudo apt-get update -qq
  - sudo apt-get install gcc-4.7 g++-4.7 cmake libboost-system1.48-dev libopenimageio-dev
script:
  - cmake -DCMAKE_CXX_COMPILER=g++-4.7 -DCMAKE_C_COMPILER=gcc-4.7
  - make
