sudo: required
dist: trusty
language: cpp
compiler:
  - clang
  - gcc
install:
  - sudo apt-get update -qq
  - sudo apt-get install git cmake libboost-dev libboost-filesystem-dev libboost-regex-dev libboost-system-dev libboost-thread-dev --yes
before_script:
# clone openimageio and build/install
  - git clone https://github.com/OpenImageIO/oiio.git --branch RB-1.4 --depth 1
  - cd oiio
  - git apply ../oiio.patch
  - sudo make USE_QT=0 USE_OPENGL=0 USE_PYTHON=0 USE_FIELD3D=0 USE_OPENJPEG=0 USE_GIF=0 USE_OCIO=0 USE_OPENSSL=0 USE_LIBRAW=0 NOTHREADS=0 OIIO_BUILD_TOOLS=0 OIIO_BUILD_TESTS=0 -e dist_dir= INSTALLDIR=/usr
  - cd ..
script:
  - cmake ./
  - make

