language: cpp
compiler:
  - clang
  - gcc
before_script:
# gcc 4.7
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test --yes
  - sudo add-apt-repository ppa:irie/openimageio --yes
  - sudo apt-get update -qq
  - sudo apt-get build-dep -y openimageio
  - sudo apt-get install -y gcc-4.7 g++-4.7 cmake git
  - git clone -b RB-1.4 https://github.com/OpenImageIO/oiio.git
  - cd oiio
  - sudo make -e dist_dir= INSTALLDIR=/usr
  - cd ..
script:
  - cmake -DCMAKE_CXX_COMPILER=g++-4.7 -DCMAKE_C_COMPILER=gcc-4.7
  - make
